/**
 * Class: InvalidHourFormatException
 * Description: Used to throw an exception if there is an internal error with the hour format for shifts
 * 
 * @author Marton Marek
 */

package application.exceptions;


public class InvalidHourFormatException extends Exception {

	/**
	 * Autogenerated default serial version ID
	 */
	private static final long serialVersionUID = 1L;

	public InvalidHourFormatException(String message) {
		super(message);
	}
	
}
