/**
 * Class: InvalidBedIndexException
 * Description: Used to throw invalid bed ID exceptions 
 * 
 * @author Marton Marek
 */

package application.exceptions;


public class InvalidBedIndexException extends Exception {

	
	/**
	 * Autogenerated default serial version ID
	 */
	private static final long serialVersionUID = 1L;

	public InvalidBedIndexException(String message) {
		super(message);
	}
}
