/**
 * Class: OutsideOfShiftTimeException
 * Description: Used to throw an exception when the current user is trying to perform an action
 * outside of their shift hours or trying to log into the system outside of their shift hours. 
 * 
 * @author Marton Marek
 */

package application.exceptions;


public class OutsideOfShiftTimeException extends Exception {

	/**
	 * Autogenerated default serial version ID
	 */
	private static final long serialVersionUID = 1L;
	
	public OutsideOfShiftTimeException (String message) {
		super(message);
	}

}
