/**
 * Class: ScheduleOutOfComplianceException
 * Description: This exception is thrown when the current set schedule is out of compliance. (ie. for compliance there
 * needs to be at least one nurse assigned to each morning and afternoon shift AND at least one doctor assigned to
 * a shift per day).
 * 
 * @author Marton Marek
 */


package application.exceptions;


public class ScheduleOutOfComplianceException extends Exception {

	/**
	 * Autogenerated default serial version ID
	 */
	private static final long serialVersionUID = 1L;
	
	public ScheduleOutOfComplianceException (String message) {
		super(message);
	}

}
