/**
 * Abstract Class: AbstractUser
 * Description: Defined the minimum attributes that a user must have for the system. 
 * Each user type can extend this to add further attributes/ functionality specific to them. 
 * 
 * @author Marton Marek
 */

package application;

import java.io.Serializable;
import java.time.LocalDate;
import java.util.UUID;

public abstract class AbstractUser implements Serializable {

	/**
	 * Autogenerated default serial version ID
	 */
	private static final long serialVersionUID = 1L;
	
	//General Attributes 
	String firstName;
	String surname;
	String job;
	LocalDate dob;
	
	//login attributes
	String username;
	String password;
	
	//unique ID
	UUID uuid;
	String employeeID;
	
	/**
	 * Default Contructor 
	 * @param firstName
	 * @param surname
	 * @param username
	 * @param password
	 * @param dob
	 */
	public AbstractUser(String firstName, String surname, String username, String password, LocalDate dob) {
		super();
		this.firstName = firstName;
		this.surname = surname;
		this.username = username;
		this.password = password;
		this.dob = dob;
		this.job = "Manager";		
		uuid = UUID.randomUUID();
		employeeID = uuid.toString();
	}
	
	/**
	 * Constructor with job role included
	 * @param firstName
	 * @param surname
	 * @param username
	 * @param password
	 * @param dob
	 * @param job
	 */
	public AbstractUser(String firstName, String surname, String username, String password, LocalDate dob, JobRole job) {
		super();
		this.firstName = firstName;
		this.surname = surname;
		this.username = username;
		this.password = password;
		this.dob = dob;
		this.job = job.jobName;
		uuid = UUID.randomUUID();
		employeeID = uuid.toString();
	}
	

	/**
	 * Getter and Setter methods 
	 */
	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String name) {
		this.firstName = name;
	}
	
	public String getSurname() {
		return surname;
	}

	public void setSurname(String name) {
		this.surname = name;
	}


	public String getUsername() {
		return username;
	}


	public void setUsername(String username) {
		this.username = username;
	}


	public String getPassword() {
		return password;
	}


	public void setPassword(String password) {
		this.password = password;
	}
	
	public String getEmployeeID() {
		return employeeID;
	}

	public String getJob() {
		return job;
	}

	public void setJob(String job) {
		this.job = job;
	}

	public LocalDate getDob() {
		return dob;
	}

	public void setDob(LocalDate dob) {
		this.dob = dob;
	}
	
	
	
 }
