/**
 * Class: Main
 * Description: This is the main class of the application. It is responsible for starting the application
 * via the main method. It also holds the capability to switch between main screens like the login screen
 * and the main application screen (or others in future).
 * 
 * @author Marton Marek
 */

package application;
	
import java.io.*;
import javafx.application.Application;
import javafx.stage.Stage;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.fxml.FXMLLoader;


public class Main extends Application implements Serializable {
	
	/**
	 * Autogenerated default serial version ID
	 */
	private static final long serialVersionUID = 1L;
	
	//used to move between login screen and main screen
	private static Stage stage;
		
	//the interface
	@Override
	public void start(Stage primaryStage) {
		try {
			stage = primaryStage;
			primaryStage.setResizable(false);
			Parent root = FXMLLoader.load(getClass().getResource("Login.fxml"));
			Scene scene = new Scene(root,600,320);
			scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
			primaryStage.setScene(scene);
			primaryStage.setTitle("Resi-Care v0.1 Login");
			primaryStage.show();
		} catch(Exception e) {
			e.printStackTrace();
		}
	}
	
	/**
	 * This will change the main screen based on the input fxml file. The provided
	 * height and width will determine the size of the new screen being generated
	 * 
	 * @param fxmlFile
	 * @param title
	 * @param width
	 * @param height
	 * @throws IOException
	 */
	public void sceneChange(String fxmlFile, String title, int width, int height) throws IOException {
		Parent root = FXMLLoader.load(getClass().getResource(fxmlFile));
		stage.getScene().setRoot(root);
		stage.setWidth(width);
		stage.setHeight(height);
		stage.setTitle(title);
	}
	
	/**
	 * This is the main method where it all begins..
	 * @param args
	 */
	public static void main(String[] args) {
		
		try {		
			//launches our interface gui
			launch(args);
			
			//save the file before exit
			CareHome.getInstance().saveToFile();
		}
		catch (Exception e) {
			System.out.println("Critical system error: " + e.getMessage());
		}

	}
}
