/**
 * Class: Manager
 * Description: This holds the details of a Manager object. On very first load of the 
 * application. A "defaultmanager" will be created with default username and password as "admin"
 * This default manager can then add the first real manager. Who can then delete the default.
 * 
 * @author Marton Marek
 */

package application;

import java.time.LocalDate;

public class Manager extends AbstractUser {

	/**
	 * Autogenerated default serial version ID
	 */
	private static final long serialVersionUID = 1L;
	
	
	/**
	 * Default constructor that is used at first load of the application (When there are no users created yet)
	 * @param firstName
	 * @param surname
	 */
	public Manager(String firstName, String surname) {
		super(firstName, surname, "admin", "admin", null, JobRole.ADMIN);
	}
	
	/**
	 * Constructor that is used when a manager created a new user
	 * @param firstName
	 * @param surname
	 * @param username
	 * @param password
	 * @param dob
	 */
	public Manager(String firstName, String surname, String username, String password, LocalDate dob) {
		super(firstName, surname, username, password, dob, JobRole.ADMIN);
	}
		
	
}
