/**
 * Class: Medicine
 * Description: This holds the details of a medicine (its name) and can be identified by a unique ID.
 * 
 * @author Marton Marek
 */

package application;

import java.io.Serializable;
import java.util.UUID;

public class Medicine implements Serializable {

	/**
	 * Autogenerated default serial version ID
	 */
	private static final long serialVersionUID = 1L;

	//the name of the medicine
	String name;
	
	//unique ID
	UUID uuid;
	String medID;
	
	/**
	 * Default constructor 
	 */
	public Medicine() {
	}
	
	/**
	 * Constructor providing the name of the medicine. 
	 * @param name
	 */
	public Medicine(String name) {
		uuid = UUID.randomUUID();
		medID = uuid.toString();
		
		this.name = name;
	}

	/**
	 * Getters and Setter methods
	 * @return
	 */
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	
}
