/**
 * Class: Nurse
 * Description: Defines a nurse class based on the medicalstaff superclass. It defines the shift
 * length for a nurse and the allowed shift start times. 
 * 
 * @author Marton Marek
 */

package application;

import java.time.LocalDate;

public class Nurse extends MedicalStaff {

	/**
	 * Autogenerated default serial version ID
	 */
	private static final long serialVersionUID = 1L;
	
	public static final int NURSE_SHIFT_LENGTH = 8; //nurse shift are 8 hours long
	public static final int NURSE_SHIFT_MORNING_START = 8;
	public static final int NURSE_SHIFT_NIGHT_START = 14;
	
	/**
	 * Default constructor 
	 * @param firstName
	 * @param surname
	 * @param username
	 * @param password
	 * @param dob
	 */
	public Nurse(String firstName, String surname, String username, String password, LocalDate dob) {
		super(firstName, surname, username, password, dob, JobRole.NURSE);
		initialiseStartTimes();
		shiftLength = NURSE_SHIFT_LENGTH;
	}
	
	/**
	 * Implements the abstract method from superclass. This defines all a list of 
	 * all possible start times for a nurses shift. Once this is initialised, the shift times
	 * can be defined using these as selection options. 
	 */
	protected void initialiseStartTimes() {
		allowedShiftStartTimes = new int[3];
		allowedShiftStartTimes[0] = 0;  //means no shift
		allowedShiftStartTimes[1] = NURSE_SHIFT_MORNING_START;
		allowedShiftStartTimes[2] = NURSE_SHIFT_NIGHT_START;
	}

}
