/**
 * Class: Prescription
 * Description: Holds the details of a prescription, including the medicine, dose, and the recurrence. 
 * 
 * @author Marton Marek
 */

package application;

import java.io.Serializable;
import java.util.UUID;

public class Prescription implements Serializable {

	/**
	 * Autogenerated default serial version ID
	 */
	private static final long serialVersionUID = 1L;
	
	Medicine medicine;
	Dose dose;
	String recurrence;
	
	//unique ID
	UUID uuid;
	String prescriptionID;


	/**
	 * Default Constructor
	 * @param medicine
	 * @param dose
	 * @param recurrence
	 */
	public Prescription(Medicine medicine, Dose dose, String recurrence) {
		super();
		this.medicine = medicine;
		this.dose = dose;
		this.recurrence = recurrence;
		uuid = UUID.randomUUID();
		prescriptionID = uuid.toString();
	}
	
	/**
	 * override toString so we can return the prescription as one single string
	 */
	public String toString() {
		return medicine.getName() + ": " + dose.toString() + ", " + recurrence;
	}

	/**
	 * Getters and Setter methods
	 * @return
	 */
	public Medicine getMedicine() {
		return medicine;
	}

	public void setMedicine(Medicine medicine) {
		this.medicine = medicine;
	}

	public Dose getDose() {
		return dose;
	}

	public void setDose(Dose dose) {
		this.dose = dose;
	}

	public String getRecurrence() {
		return recurrence;
	}

	public void setRecurrence(String recurrence) {
		this.recurrence = recurrence;
	}
	
	public String getMedicineName() {
		return medicine.getName();
	}
	
	public String getDoseDay() {
		String day = dose.getDay().toString();
		//convert first letter to uppercase and rest to lower case
		return day.substring(0,1).toUpperCase() + day.substring(1).toLowerCase();
	}
	
	public String getDoseTime() {
		return String.valueOf(dose.getTime() + ":00"); 
	}
	
	public String getDoseAmount() {
		return String.valueOf(dose.getDose());
	}
	
	public String getPrescriptionID() {
		return prescriptionID;
	}
	
}
