/**
 * Class: Shift
 * Description: Holds the Day, start and end hour of a shift and the shift legnth in hours. 
 * 
 * @author Marton Marek
 */

package application;

import java.io.Serializable;


public class Shift implements Serializable {
	
	/**
	 * Autogenerated default serial version ID
	 */
	private static final long serialVersionUID = 1L;

	//day of the shift
	Day day;
	
	//start hour of the shift
	int shiftStartHour;
	
	//end hour of the shift
	int shiftEndHour;
	
	//length of the shift in hours
	int shiftLength;

	/**
	 * Default Constructor 
	 * @param day
	 */
	public Shift(Day day) {
		this.day = day;
		
		this.shiftStartHour = 0;
		this.shiftLength = 0;
		this.shiftEndHour = 0;
	}
	
	/**
	 * Getters and Setter methods
	 * @return
	 */

	public Day getDay() {
		return day;
	}

	public void setDay(Day day) {
		this.day = day;
	}

	public int getShiftStartHour() {
		return shiftStartHour;
	}
	
	public void setShiftStartHour(int shiftStartHour) {
		this.shiftStartHour = shiftStartHour;
	}
	
	public String getShiftStartHourString() {
		if (shiftStartHour == 0) {
			return "None";
		}
		else {
			return String.valueOf(shiftStartHour + ":00");
		}
	}
	
	public int getShiftEndHour() {
		return shiftEndHour;
	}
	
	public void setShiftEndHour(int shiftEndHour) {
		this.shiftEndHour = shiftEndHour;
	}
	
	public String getShiftEndHourString() {
		if (shiftEndHour == 0) {
			return "None";
		}
		else {
			return String.valueOf(shiftEndHour + ":00");
		}
	}

	public int getShiftLength() {
		return shiftLength;
	}

	public void setShiftLength(int shiftLength) {
		this.shiftLength = shiftLength;
	}
}
